### ISSUE TITLE
Add Website Files

### ISSUE THREAD

**Issue by ElementalDev** [ElementalDev/elementalnecro.github.io#1]
## TODO
* [ ] Download files from 1and1
* [ ] unpack the files
* [ ] create a git repo on them in ubuntu
* [ ] commit the files
* [ ] Add the remote repo elementalnecro.github.io
* [ ] Push the files to the remote repo
* [ ] DONE :1st_place_medal:
